apiVersion: apps/v1
kind: Deployment
metadata:
   name: devops-1
spec:
   replicas: 2
   selector:      # tells the controller which pods to watch/belong to
    matchLabels:
     app: devops-1
   template:
      metadata:
        labels:
          app: devops-1
      spec:
       containers:
        - name: devops-cont
          image: harikrishnachandra5434/kb-job-1
          imagePullPolicy: Always
          ports:
          - containerPort: 80